package_assets: on # (on, off, always)
embed_assets: on # (on, off, datauri)
compress_assets: on # (on, off)
gzip_assets: on # (on, off)
template_function: off # (defaults to the built-in micro-templating)
package_path: assets # (defaults to assets)
javascript_compressor: yui # (yui, closure)

javascripts:
  global:
    - public/javascripts/jquery-1.6.1.min.js
    - public/javascripts/jquery-ui-1.8.14.custom.min.js
    - public/javascripts/jquery.countdown.min.js
    - public/javascripts/jquery.fancybox-1.3.4.pack.js
    - public/javascripts/supersized.core.3.2.1.js
    - public/javascripts/jqFancyTransitions.1.8.min.js
    - public/javascripts/jquery.tablesorter.min.js
    - public/javascripts/jquery.multiselect.min.js
    - public/javascripts/jquery.multiselect.filter.min.js
    - public/javascripts/jquery.ui.timepicker.js
    - public/javascripts/jquery.scrollTo-min.js
    - public/javascripts/jquery.localscroll-min.js
    - public/javascripts/jquery.formatCurrency-1.4.0.min.js
    - public/javascripts/rails.validations.js
    - public/javascripts/jtip.js
    - public/javascripts/custom.js
    - public/javascripts/rails.js

stylesheets:
  global:
    - public/stylesheets/style.css
    - public/stylesheets/typography.css
    - public/stylesheets/jquery-ui-1.8.14.custom.css
    - public/stylesheets/jquery.fancybox-1.3.4.css
    - public/stylesheets/jquery.countdown.css
    - public/stylesheets/jquery.multiselect.css
    - public/stylesheets/jquery.multiselect.filter.css
    - public/stylesheets/jquery-ui-timepicker.css
    - public/stylesheets/jtip.css

