class PopulateReference
  def self.populate_all
    Gender.find_or_create_by_name("Select Gender")
    Gender.find_or_create_by_name("Male")
    Gender.find_or_create_by_name("Female")
    Gender.find_or_create_by_name("Prefer not to share")
    
    Education.find_or_create_by_name("Select Education Level")
    Education.find_or_create_by_name("Some high school")
    Education.find_or_create_by_name("High school grad or equivalent")
    Education.find_or_create_by_name("Trade or vocational")
    Education.find_or_create_by_name("Some college")
    Education.find_or_create_by_name("Associates degree")
    Education.find_or_create_by_name("Bachelors degree")
    Education.find_or_create_by_name("Professional degree")
    Education.find_or_create_by_name("Prefer not to share")
    
    Employment.find_or_create_by_name("Select Employment Status")
    Employment.find_or_create_by_name("Full-time")
    Employment.find_or_create_by_name("Part-time")
    Employment.find_or_create_by_name("Looking for work")
    Employment.find_or_create_by_name("Not looking for work")
    Employment.find_or_create_by_name("Retired")
    Employment.find_or_create_by_name("Student")
    Employment.find_or_create_by_name("Homemaker")
    Employment.find_or_create_by_name("Prefer not to share")
    
    Income.find_or_create_by_name("Select Income Level")
    Income.find_or_create_by_name("Under $20k")
    Income.find_or_create_by_name("$20k - $30k")
    Income.find_or_create_by_name("$30k - $40k")
    Income.find_or_create_by_name("$40k - $50k")
    Income.find_or_create_by_name("$50k - $70k")
    Income.find_or_create_by_name("$70k - $100k")
    Income.find_or_create_by_name("$100k - $150k")
    Income.find_or_create_by_name("Over $150k")
    Income.find_or_create_by_name("Prefer not to share")
    
    House.find_or_create_by_name("Select Living Situation")
    House.find_or_create_by_name("Rent")
    House.find_or_create_by_name("Own")
    House.find_or_create_by_name("Prefer not to share")
    
    RelationshipStatus.find_or_create_by_name("Select Relationship Status")
    RelationshipStatus.find_or_create_by_name("Single")
    RelationshipStatus.find_or_create_by_name("Attached")
    RelationshipStatus.find_or_create_by_name("Married")
    RelationshipStatus.find_or_create_by_name("Separated")
    RelationshipStatus.find_or_create_by_name("Divorced")
    RelationshipStatus.find_or_create_by_name("Widowed")
    RelationshipStatus.find_or_create_by_name("Prefer not to share")
    
    Children.find_or_create_by_name("Select Parental Status")
    Children.find_or_create_by_name("Yes")
    Children.find_or_create_by_name("No")
    Children.find_or_create_by_name("Prefer not to share")
    
    City.find_or_create_by_name_and_active("New York City", true)
    City.find_or_create_by_name_and_active("Philadelphia", false)
    City.find_or_create_by_name_and_active("Boston", false)
    City.find_or_create_by_name_and_active("Washington, DC", false)
    City.find_or_create_by_name_and_active("Baltimore", false)
    City.find_or_create_by_name_and_active("Atlanta", false)
    City.find_or_create_by_name_and_active("Austin", false)
    City.find_or_create_by_name_and_active("Chicago", false)
    City.find_or_create_by_name_and_active("Dallas", false)
    City.find_or_create_by_name_and_active("Houston", false)
    City.find_or_create_by_name_and_active("Los Angeles", false)
    City.find_or_create_by_name_and_active("Miami", false)
    City.find_or_create_by_name_and_active("Phoenix", false)
    City.find_or_create_by_name_and_active("San Fransisco", false)
    City.find_or_create_by_name_and_active("Seattle", false)
    
    Amenity.find_or_create_by_name("Full Bar")
    Amenity.find_or_create_by_name("Kitchen/Food")
    Amenity.find_or_create_by_name("BYOB")
    Amenity.find_or_create_by_name("All Ages")
    Amenity.find_or_create_by_name("Over 18")
    Amenity.find_or_create_by_name("Over 21")
    
    BankAccountType.find_or_create_by_name("Checking")
    BankAccountType.find_or_create_by_name("Savings")
    BankAccountType.find_or_create_by_name("Other")
    
    CreditCardType.find_or_create_by_name_and_display_name("visa", "Visa")
    CreditCardType.find_or_create_by_name_and_display_name("master", "MasterCard")
    CreditCardType.find_or_create_by_name_and_display_name("american_express", "American Express")
    CreditCardType.find_or_create_by_name_and_display_name("discover", "Discover")
    
    PaymentType.find_or_create_by_name("Please Choose...")
    PaymentType.find_or_create_by_name("Direct Deposit")
    PaymentType.find_or_create_by_name("Paper Check via USPS")
    PaymentType.find_or_create_by_name("Paypal")
    
    EventType.find_or_create_by_name_and_active("Live Music", true)
    EventType.find_or_create_by_name_and_active("Theater", true)
    EventType.find_or_create_by_name_and_active("Comedy", true)
   
  end
end
